import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>here we can put our shared layout for entire app...</nav>
        {children}</body>
    </html>
  )
}
